version: '3'
services:
  db:
    hostname: primary
    image: sogis/oereb-db:latest
    environment:
      PG_DATABASE: oereb
      PG_LOCALE: de_CH.UTF-8
      PG_PRIMARY_PORT: 5432
      PG_MODE: primary
      PG_USER: admin
      PG_PASSWORD: admin
      PG_PRIMARY_USER: repl
      PG_PRIMARY_PASSWORD: repl
      PG_ROOT_PASSWORD: secret
      PG_WRITE_USER: gretl
      PG_WRITE_PASSWORD: gretl
      PG_READ_USER: ogc_server
      PG_READ_PASSWORD: ogc_server
    ports:
      - "54321:5432"
    volumes:
      - ~/tmp/oereb-pgdata:/pgdata
  web-service:
    depends_on:
      - db
    hostname: web-service
    image: sogis/oereb-web-service:latest
    environment:
      DBURL: jdbc:postgresql://db:5432/oereb
      DBUSR: admin
      DBPWD: admin
      DBSCHEMA: live
    ports:
      - "8080:8080"
