version: '3'
services:
  db:
    hostname: primary
    image: sogis/oereb-db-data:2019-10-25_205953
    environment:
      PG_DATABASE: oereb
      PG_LOCALE: de_CH.UTF-8
      PG_PRIMARY_PORT: 5432
      PG_MODE: primary
      PG_USER: admin
      PG_PASSWORD: admin
      PG_PRIMARY_USER: repl
      PG_PRIMARY_PASSWORD: repl
      PG_ROOT_PASSWORD: secret
      PG_WRITE_USER: gretl
      PG_WRITE_PASSWORD: gretl
      PG_READ_USER: ogc_server
      PG_READ_PASSWORD: ogc_server
    ports:
      - "54322:5432"
    restart: always
  wms:
    #image: sogis/oereb-wms:latest
    #image: sogis/oereb-wms:c39fa21
    image: sogis/oereb-wms:5fad780
    environment:
      QGIS_SERVER_PARALLEL_RENDERING: "true"
      QGIS_SERVER_MAX_THREADS: 2
      QGIS_FCGI_MAX_PROCESSES: 2
      QGIS_FCGI_MIN_PROCESSES: 2
      QGIS_SERVER_LOG_LEVEL: 0
    ports:
      - 8083:80
    depends_on:
      - db
  oereb-web-service:
    hostname: oereb-web-service
    image: sogis/oereb-web-service:latest
    environment:
      TZ: Europe/Zurich
      DBURL: jdbc:postgresql://db:5432/oereb
      DBUSR: admin
      DBPWD: admin
      TMPDIR: /home/oereb-web-service
      DBSCHEMA: live
      MININTERSECTION: "0.1"
      #SERVER_SERVLET_CONTEXT_PATH: /ws
      SERVER_PORT: 8181
      #LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: DEBUG
      #LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_JDBC_CORE: TRACE
    ports:
      - "8181:8181"
    depends_on:
      - db
    restart: always
  cadastral-web-service:
    hostname: cadastral-web-service
    image: sogis/cadastral-web-service:latest
    environment:
      TZ: Europe/Zurich
      SPRING_PROFILES_ACTIVE: dev
      DBUSR: admin
      DBPWD: admin
      DBURL: jdbc:postgresql://db:5432/oereb
      SERVER_PORT: 8484
    ports:
      - "8484:8484"
    depends_on:
      - db
    restart: always
  client:
    depends_on:
      - oereb-web-service
      - cadastral-web-service
    image: sogis/oereb-client:latest
    environment:
      SERVER_PORT: 8282
      OEREB_WEB_SERVICE_URL_SERVER: http://oereb-web-service:8181/
      OEREB_WEB_SERVICE_URL_CLIENT: http://oereb.sogeo.services/ws/
      SEARCH_SERVICE_URL: https://geo.so.ch/api/search/v2/?filter=ch.so.agi.av.grundstuecke.rechtskraeftig,ch.so.agi.av.gebaeudeadressen.gebaeudeeingaenge&limit=10&searchtext=
      SEARCH_SERVICE_PATH: search/
      DATA_SERVICE_URL: https://geo.so.ch/api/data/v1/
      BACKGROUND_WMTS_URL: https://geo.so.ch/api/wmts/1.0.0/{Layer}/default/2056/{TileMatrix}/{TileRow}/{TileCol}
      BACKGROUND_WMTS_LAYER: ch.so.agi.hintergrundkarte_sw
      WMS_HOST_MAPPING: "{'http://wms:80/wms/oereb':'http://oereb.sogeo.services/wms/oereb'}"
      CADASTRAL_SURVEYING_SERVICE_URL: http://cadastral-web-service:8484/extract/
      CADASTRAL_SURVEYING_PARCEL_URL: http://oereb.sogeo.services/parcel/getparcel
    ports:
      - "8282:8282"
    restart: always  
  parcel-info-service:
    hostname: parcel-info-service
    image: sogis/parcel-info-service:latest
    environment:
      TZ: Europe/Zurich
      DBURL: jdbc:postgresql://db:5432/oereb
      DBUSR: admin
      DBPWD: admin
      DBSCHEMA: live
      SERVER_PORT: 8585
    ports:
      - "8585:8585"
    depends_on:
      - db
    restart: always      
  proxy:
    image: abiosoft/caddy:latest
    #environment:
    #  ACME_AGREE: "true"
    restart: always
    ports:
      - "80:80"
      #- "443:443"
    volumes:
      #- "/private/caddy_prod/.caddy:/root/.caddy"
      #- "./caddy/Caddyfile:/etc/Caddyfile"
      #- "/private/caddy_prod/Caddyfile:/etc/Caddyfile"
      - "./caddy/Caddyfile:/etc/Caddyfile"
